### ISSUE TITLE
Scaling of ExpandBar not working properly after DPI change

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#103]
Scaling of ExpandBar broke over time:

![Image](https://github.com/user-attachments/assets/8908bcc5-d4bc-42da-ba98-cec6e1b47b19)

Scenario was here to start on 200% and move over to 100%

**Comment by ShahzaibIbrahim** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1528
