### ISSUE TITLE
Wrong layout of CTabFolder on non primary monitor when unlocking the laptop

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#110]
I had my IDE on the non primary monitor and locked it. After unlocking it looked like that. 

![Image](https://github.com/user-attachments/assets/9b7ef9de-7b0a-402f-b92c-abb90f291443)

**Comment by akoch-yatta** [comment]
Probably the same issue that was solved with #118. I will recheck with a renewed RCP

**Comment by HeikoKlare** [comment]
I would also expect this to be solved together with #118. Would be great if you can reevaluate, @akoch-yatta

**Comment by akoch-yatta** [comment]
As I didn't have a reproducible scenario, I cannot say, what the issue caused and if it is gone. But as i didn't have it since quite some time, I will close this as hopefully solved.

**Comment by HeikoKlare** [comment]
Might have implicitly been fixed via https://github.com/eclipse-platform/eclipse.platform.swt/pull/1531
