### ISSUE TITLE
Layout for radio and checkbox label in Manifest overview page

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#114]
Setup:

Two Monitors:
Monitor 1: 200%
Monitor 2: 100%, primary monitor

![Image](https://github.com/user-attachments/assets/813b7244-fc8d-41de-8373-0769057de4a9)

I don't know what the used SWT elements are here, but you see the effect in the overview page for Manifest.MF

**Comment by ShahzaibIbrahim** [comment]
Affected due to this PR: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1314

**Comment by akoch-yatta** [comment]
Will be solved with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1506

**Comment by akoch-yatta** [comment]
#1506 is merged
