### ISSUE TITLE
Toolbar Rescaled Improperly when Zoom of Other Monitor is Changed

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-Platform#118]
The main toolbar is rescaled improperly when the workbench window is placed on a secondary monitor while the zoom value of the primary monitor is changed. E.g. consider the following setup:
- Two monitors, primary monitor at 125%, secondary monitor at 100%
- Start Eclipse application with rescale on runtime activate and auto scale mode `quarter`
- Place the workbench window on secondary monitor
- Change zoom value of primary monitor from 125% to 150%

This is the result:\
![Image](https://github.com/user-attachments/assets/1ced380c-820b-4cd5-b73e-8535c3673900)

Sometimes this does not happen on first execution of the process. Repeatedly changing the primary monitor zoom between 125% and 150% will eventually result in the problematic state.

My impression is that some refresh operation is not executed. Simply rescaling the window, maximizing it or the like resolves the problem.

**Addition**: Changing the primary monitor zoom while having a window placed on another monitor seems to have more unintended effects. The window is rescaled even though the monitor is not affected at all. Also rescaling issues in other widgets occur, see, e.g.,  the onboarding area:

![Image](https://github.com/user-attachments/assets/64b9d044-ca18-4792-bda1-e85ee6275052)

**Comment by akoch-yatta** [comment]
Should be fixed by https://github.com/eclipse-platform/eclipse.platform.swt/pull/1531

**Comment by akoch-yatta** [comment]
PR was merged. Should be monitored with next nightly build
