### ISSUE TITLE
Add experimental preference to enable update on runtime behavior

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#134]
Where: 
UI:
- Preferences -> General -> Appereance
- Best case: Preference is only visible on Windows

Code:
- perhaps org.eclipse.e4.ui.swt.win32

What is affected:
- swt.autoscale: if not active -> change nothing, if active -> change
- Browser: , swt.autoscale, swt.autoscale.updateOnRuntime

What:
- Evaluate preference at workbench initialization: 
- configure Display accordingly: Display::setRescalingAtRuntime
- Edge as default browser -> Set the system property "org.eclipse.swt.browser.DefaultType" to edge

This preference must be disabled by default

**Comment by fedejeanne** [comment]
@akoch-yatta can you please add a description for this and a size estimation? I assume is "small" / "tiny" but we probably need to test accordingly and give it time to find possible side-effects.
