### ISSUE TITLE
Toolbar Icons in View Stacks Have White Background After Rescaling

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-Platform#139]
Preconditions:
- Two monitors with different scale values (e.g., 100% and 125%)
- "Rescaling on runtime" feature activated

When moving a workbench window from one monitor to another, the background of the toolbar icons becomes white, while it is properly transparent on the monitor on which the workbench window first shows up. Interestingly, this _also_ appears with autoScale mode `integer200` and two monitor with scale values that do not require any rescaling of the images (e.g., 100% and 125%).

SWT autoScale mode set to `quarter`:
![Image](https://github.com/user-attachments/assets/2749584f-8465-4077-b4a7-702141e39034)

SWT autoScale mode set to `integer200`:
![Image](https://github.com/user-attachments/assets/9887f140-6227-4cf0-b465-c635da892733)

**Comment by akoch-yatta** [comment]
I had a look into it. It seems to be related to the background "configuration" of the toolbar (image, alpha, etc.), but this needs further investigation, so I put it to 4.35M1
