### ISSUE TITLE
Edge browser: activate tests

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#152]

**Comment by fedejeanne** [comment]
@HeikoKlare IIRC you wanted to take care of this one?

If not, remove yourself as _Assignee_.

**Comment by HeikoKlare** [comment]
No, this issue is open to be picked by anyone having time to address it. It is of highest priority, so we should not wait for anyone specific to work on it.

**Comment by HeikoKlare** [comment]
Experiments on this issue can be found here: https://github.com/eclipse-platform/eclipse.platform.swt/pull/672

Still, some tests fail undeterministically in GitHub Actions. Locally, they usually run fine. We need to investigate why they fail and resolve the causing issue.
