### ISSUE TITLE
Analyse Display::getDPI contract

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#155]
With https://github.com/eclipse-platform/eclipse.platform.swt/pull/1342/files#diff-02eb2e52f3bbbefb895d83469765ce42bf690a2430e4a83fcf5b0d60c036f73b the return value of Display::getDPI was changed and can return a different value than before with zoom level != 100. Reverting it does not seem as the correct solution either, because the assumption is, that the previous implementation could return "wrong" values as well in some scenarios. 

To proceed we need to first analyse the "real" contract of that method:
- based on an the existing usages in the Platform SDK and GEF (**note:** most usages are related to printing)
- based on the implementations in GTK/cocoa

**Any findings should be documented and probably discussed in a further weekly**

**Important:** CTabFolderRenderer::getChevronFont uses this method -> This relationship should probably be replaced and the font size should be calculated another way

Probable solution could mean reverting the getDPI method to the previous implementation and introducing a new API method with a new implementation the avoid further regressions in existing implementation.

**Comment by amartya4256** [comment]
After trying out different scenarios for how getDPI works, I found the following:

- On using the scaleDown with native zoom, the DPI values are different and that causes a visible indentation difference in the texts, so it makes sense to use the device zoom how it was done earlier.
- To get rid of the autoScaleDown method calls in win32, we must use `DPIUtil.scaleDown(new Point (dpiX, dpiY), DPIUtil.getZoomForAutoscaleProperty(getDeviceZoom()))`, which returns the same value as DPIUtil.scaleDown
- No other visible effects were found, however, the header nopt being placed on printing the code is confirmed to be not caused because of the getDPI chnages and hence I will create a new ticket for that issue.

**Comment by HeikoKlare** [comment]
@amartya4256 Is it really the right thing to just revert `getDPI()` to it's old implementation? When using monitor-specific scaling, the result seems to be rather useless to me, as it will (only) depend on the current (random) `nativeZoom` in `DPIUtil`. Thus it "randomly" changes upon interactions with different monitors, potentially leading to unexpected results.
Note that `OS.GetDeviceCaps (hDC, OS.LOGPIXELSX)` also seems to return the same value througout the application lifecycle, no matter what scaling the primary monitor has, which is somehow unexpected, as the the implementation seems to be expect that value to be somehow consistent with the `nativeZoom` in `DPIUtil`.

**Comment by akoch-yatta** [comment]
Isn't this whole method quite useless in the monitor-specific scaling anyway? Reverting the old implementation "fixes" the regression, We could add a different behavior for the monitor-specific scaling active, but I did and do not see any useable implementation here, because whatever you do, it will be wrong in a lot of scenarios. 
Regarding `OS.GetDeviceCaps (hDC, OS.LOGPIXELSX)` I agree that the behavior seems to be weird. Did you verify you saw the same behavior for OS.LOGPIXELSX remaing unchanged @amartya4256 ?

**Comment by akoch-yatta** [comment]
But we could target the usages of getDPI directly. At least in the Platform there are not many.

**Comment by HeikoKlare** [comment]
> Isn't this whole method quite useless in the monitor-specific scaling anyway? 

Probably, yes. But then it might be necessary to deprecate that method and replace its usages, as whatever contract consumers may currently expect for this method, it will break once they use monitor-specific scaling.

**Comment by HeikoKlare** [comment]
Created for the mentioned follow-up actions:
- #179
