### ISSUE TITLE
Images not aligned in Help Context Menu

### ISSUE THREAD

**Issue by ShahzaibIbrahim** [vi-eclipse/Eclipse-Platform#169]
Moving from Secondary (200) to Primary (150) Help - > Show Context Help -> Images not scaled or aligned
image.

![Image](https://github.com/user-attachments/assets/37bac60e-7961-4ceb-ae9a-24be3863fb2b)

**Comment by ShahzaibIbrahim** [comment]
Only happens in case of Integer200. **Fixed** on quarter scaling.

**Comment by HeikoKlare** [comment]
@ShahzaibIbrahim Isn't the alignment still somehow wrong when using `integer200`?

**Comment by ShahzaibIbrahim** [comment]
@HeikoKlare yes, but its the case of images not scaling at all in integer200. Wasn't this issue everywhere with int200?

**Comment by HeikoKlare** [comment]
Yes, the primary purpose of integer200 is to not scale images. I was just confused by the alignment, which looks off, and was wondering whether that needs to be improved.
