### ISSUE TITLE
Add Regression Test to PR#766

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-Platform#24]
If possible, add a regression test for the changes in https://github.com/eclipse-platform/eclipse.platform/pull/766. The test should make sure that the current tab is activated (_i.e._ that its `activate` method is called) when switching between _Run Configurations_ in the _Run Configurations Dialog_

_(Moved to https://github.com/eclipse-platform/eclipse.platform/issues/1075)_

**Comment by HeikoKlare** [comment]
I propose to increase priority for this issue. The fix has been merged without an automated test and 4.30 release is about to come, so I suggest to provide a (regression) test before release,

**Comment by fedejeanne** [comment]
I'm ok with it, I just won't be working on it anytime soon since the changes were small and the functionality has been manually tested so I don't consider this a pressing matter.

I removed the assignee, this ticket can be re-prioritized and picked out.

**Comment by fedejeanne** [comment]
Waiting for https://github.com/eclipse-platform/eclipse.platform/pull/860 to be merged

**Comment by HeikoKlare** [comment]
PR has been merged

**Comment by HeikoKlare** [comment]
Added test is broken: https://github.com/eclipse-platform/eclipse.platform/issues/1075

**Comment by fedejeanne** [comment]
PR created and sent for review (@HeikoKlare ?)
