### ISSUE TITLE
Provide HiDPI Support for Multi-Monitor Environments for basic controls

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#32]
This ticket is a subtask of #4 

## Controls to adapt
The following basic controls are targeted in this ticket:

- [x] Button
- [x] Combo
- [x] Composite
- [x] CoolBar
- [x] DateTime
- [x] ExpandBar
- [x] Label
- [x] List
- [x] Menu
- [x] ProgressBar
- [x] Scale
- [x] ScrollBar
- [x] Shell
- [x] Slider
- [x] Spinner
- [x] TabFolder
- [x] Table
- [x] Text
- [x] ToolBar
- [x] Tree

## Control independent SWT behavior
Besides adjusting the controls correctly after a zoom change, the following topics will be covered in this ticket as well:

- Use appropriate system fonts after zoom changes
- Use appropriate specific fonts after zoom changes
- Handle images consistently after zoom changes 

## Out of scope
Only one zoom level is supported at the same time. If multiple shells/dialogs from the same application are displayed on monitors with different zoom levels, only the latest zoom level is considered

**Comment by HeikoKlare** [comment]
Merged: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1064
