### ISSUE TITLE
Investigate Nebula Widget for HighDPI

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#38]
Investige and adapt the Nebula Widgets (https://github.com/eclipse/nebula) in the context of HighDPI change #32, #33 and #34 

For now, we focus on the widgets used in PREEvision.

Findings are documented in Sharepoint

**Comment by HeikoKlare** [comment]
Goal: Reevaluate with current state and then close

**Comment by ShahzaibIbrahim** [comment]
Investigation completed for all the nebula widgets, some issues were non-dpi that were reported in the original repository (See: https://github.com/eclipse/nebula/issues/611, https://github.com/eclipse/nebula/issues/612) and some of the HiDpi Issues in the vi-eclipse backlog (See: https://github.com/vi-eclipse/Eclipse-Platform/issues/144, https://github.com/vi-eclipse/Eclipse-Platform/issues/145).

Additionally during testing we also found some SWT component related issues: https://github.com/vi-eclipse/Eclipse-Platform/issues/141 and https://github.com/vi-eclipse/Eclipse-Platform/issues/142
