### ISSUE TITLE
Cleanup of no longer used OS handles on zoom changes

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#42]
When a zoom changes occurs on a monitor it is possible, that some handles (e.g. fonts created for a specific zoom level) are no longer required and should be cleaned up. Some initial ideas for this:

- How to identify which zoom levels are still valid and needed? aggregation of the zoom levels of all currently used shell
- When to do the cleanup? After each DPI change event
- How to track which ressources could be cleaned up.? There is already org.eclipse.swt.graphicsResourceTracker to identify resource leaks. Perhaps this can be extanded for that behaviour

**Comment by amartya4256** [comment]
Merged with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1477
