### ISSUE TITLE
Prepare PR for adaption on StyledText

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#60]
Create PR for StyledText. Conditions are:

Minimal invasive: All changes should be checked under this condition. Prevent quality refactoring as much as possible or submit them in advance in a separate PR
Tests: Add tests to verify the behaviour when the zoom changes

PR must probably be based on PR for #43

**Comment by ShahzaibIbrahim** [comment]
Since its already addressed by @amartya4256 in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1294. Assigning it to him

**Comment by akoch-yatta** [comment]
Merged in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1294
