### ISSUE TITLE
Initialize correct zoom in TrayItem

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#63]
TrayItem extends Widget, but is not calling the super constructor, so the zoom is not inherited from its parent. 

- Initialize the zoom from its parent
- Add a Windows specific tests, that is verifying the zoom inheritance

**Note:** Tray is a common widget, so we need to have a solution for that that is **not** setting the zoom inside of the Tray class, becausei

**Comment by ShahzaibIbrahim** [comment]
The zoom looks good in my initial testing, maybe I am missing something here. 

![Image](https://github.com/user-attachments/assets/a0e7931b-3d93-4dc2-8dc4-9f400ba56501)

**Comment by ShahzaibIbrahim** [comment]
Not reproducible anymore. Closing it for now.
