### ISSUE TITLE
Toolbar of views are sometimes uneccessarily in a new line

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#66]
I can reproduce it by opening it on on 100% moving it to a bigger size and moving it back to 100, see

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/dacf4d9c-51c9-49e6-95c7-ae7494b7a646)

If you then resize the view again, it will snap back to one line, see

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/c1ae664a-1c86-4319-9463-66febf636f4e)

**Comment by ShahzaibIbrahim** [comment]
Not reproducible in my workspace. Perhaps it is fixed by other commits?

**Comment by akoch-yatta** [comment]
Couldn't reproduce it either anymore. I will close it.
