### ISSUE TITLE
Toolbar of views is sometimes overlapping

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#67]
I can reproduce it by opening it on on 100% moving it to a bigger size and moving it back to 100, see

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/ec3cb7b0-c8df-439e-b868-6317b1f6d316)

If you then resize the shell again, it will re-layout correctly

![image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/aec80614-dfc1-434b-bdbe-b90088caf28f)

**Comment by ShahzaibIbrahim** [comment]
Not reproducible in my workspace as well. Perhaps it is fixed by other commits?

**Comment by akoch-yatta** [comment]
Couldn't reproduce it either anymore. I will close it.
