### ISSUE TITLE
Incorrect scaling for TreeItem font when moving through different zoom levels

### ISSUE THREAD

**Issue by ShahzaibIbrahim** [vi-eclipse/Eclipse-Platform#74]
Not getting a new font with updated scale factor while setting up the font upon change in zoom level.

**Comment by akoch-yatta** [comment]
Merged in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1291

**Comment by ShahzaibIbrahim** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1291
