### ISSUE TITLE
Indentation in tree in Package Explorer is too big

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#82]
If I move the IDE from a 200% to 100% monitor, the indentation of the tree is way too big, see

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/db32f6ef-37b4-490c-bcbc-c926aa0310b5)

As I don't see this effect in the Outline, the issue could be in the client or the tree is just configured in a special way, that leads to this issue
![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/1739dd08-da5e-4d43-891a-69466cd65aa4)

**Comment by ShahzaibIbrahim** [comment]
![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/49493944/360e4515-b71f-4332-a21d-26281b5f83c1)

The indentation looks bad for outline as well while going to 100 from 200

**Comment by ShahzaibIbrahim** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1330

**Comment by HeikoKlare** [comment]
PR has been merged: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1330
