### ISSUE TITLE
Checkboxes and radio buttons are not correctly scaled on DPI changes

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#83]
## Description
You can see the effect in the Preferences Dialog. The height still seems to rely on the primary monitor

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/fcac0fd6-e71a-4813-b5a0-86b4fc8b56dd)

## How to reproduce
- Two monitors with 200% (primary) and 100%
- Start IDE on 200% monitor
- Open preferences dialog
- move to 100% monitor

**Comment by ShahzaibIbrahim** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1314
