### ISSUE TITLE
GC Data Image Scaling Bug

### ISSUE THREAD

**Issue by amartya4256** [vi-eclipse/Eclipse-Platform#85]
The image in GC Data is scaled with the native zoom of the GC Data instead of the zoom. This leads to the the problem of no image drawn but just a white background. The image is only visible when the zoom and nativeZoom are the same. This behavior can be seen if the IDE is started at i.e. 125% zoom level on the default monitor. Hence, in this case the zoom is set to 100 and nativeZoom is 125. And due to wrong scaling, the lineNumberRulerColumn and minimize and maximize button images are not visible but rather just a white background is visible. 

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/46150646/61c5055b-0f5c-4e19-a4c3-2fd51525df98)

**Comment by amartya4256** [comment]
The fix: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1301

**Comment by akoch-yatta** [comment]
Merged in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1301
