### ISSUE TITLE
Cut-off text when using the Notification API (vogella)

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-Platform#86]
When starting the modified version of `org.eclipse.jface.snippets.dialogs.Snippet081NotificationPopup` (provided in [comment](https://github.com/eclipse-platform/eclipse.platform.swt/issues/62#issuecomment-2178346636)) in a 150% monitor, the text is cut-off.

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/139910/0b3739b1-8798-47cc-b4b1-1bfe739b59dd)

## How to reproduce
* Update the `org.eclipse.jface.snippets.dialogs.Snippet081NotificationPopup` with the code provided in the [comment](https://github.com/eclipse-platform/eclipse.platform.swt/issues/62#issuecomment-2178346636)
* Run it

## Reproducible in
I only tested in _Windows 10_ and it's reproducible.

**Comment by ShahzaibIbrahim** [comment]
The issue exist only if **swt.autoScale** is not set to **quarter** other than that it is behaving as expected

![Image](https://github.com/user-attachments/assets/bd47fcdb-bf4b-45fb-87d7-f09836de8024)

**Comment by ShahzaibIbrahim** [comment]
Since we will hopefully have qurater autoscaling by default in the future, I would mark this issue as **wontfix**. @fedejeanne
