### ISSUE TITLE
Make Edge the Default Browser on Windows

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-Platform#90]
Currently, IE is still used as the default (SWT) browser on Windows. Since IE is end-of-life and since the new HiDPI functionality does not work properly with it (or at least requires some effort that is better put into Edge), such as scaling tooltips, the implementation used as default should be changed to Edge.

There are currently some issues prevent Edge from being used as the default browser. Most prominent one is the unability to display the IDE's welcome page, but also the inability to properly run the SWT browser tests with Edge:
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/213
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/840
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/671

The goal of this issue is to make Edge the default browser for SWT / Eclipse UI on Windows, addressing at least the above mentioned issues.

### Requires
- [x] #152
- [x] #154

### See Also
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1466

### Follow-up
- Add news entry 
- Discuss whether we want to enable the experimental "rescaling at runtime" preference afterwards

**Comment by amartya4256** [comment]
Isn't this one done as well? @fedejeanne @akoch-yatta @HeikoKlare

**Comment by fedejeanne** [comment]
Yes: https://github.com/eclipse-platform/eclipse.platform.swt/pull/672

**Comment by HeikoKlare** [comment]
We still have the follow-up open:
> Discuss whether we want to enable the experimental "rescaling at runtime" preference afterwards

**Comment by fedejeanne** [comment]
We should then agree on a methodology: "follow-up" means to me "_this_ is done but there is more to be done" so closing this issue is the right way to go IMO. 

We can discuss it in the next call.

**Comment by HeikoKlare** [comment]
> We should then agree on a methodology: "follow-up" means to me "_this_ is done but there is more to be done" so closing this issue is the right way to go IMO.

I agree, it is the right thing to do. But when closing an issue with follow-up actions, we need to ensure that those follow-up actions are actually taken as otherwise they are usually just forgotten. Do we already have something tracking those actions? I did not find anything doing it so far (a follow-up ticket, an entry in the weekly list for the discussion or the like).

**Comment by fedejeanne** [comment]
I see what you mean now.

If you add the "[ ]" to the items (in _edit_ mode) then you can _Convert them to issues_

![image](https://github.com/user-attachments/assets/0e7973cd-ee15-4bea-abe5-1cf12ae9d436)

I created 2 issues out of them.
