### ISSUE TITLE
Hover menu over methods/fields depends on wrong monitor zoom sometimes

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#93]
The "menu" (proably a shell?) that is created when hovering over e.g. methods (with CTRL pressed) is not working correctly. This seems to be related to relying on the primary monitor zoom or DPIUtil-zoom.

![Image](https://github.com/vi-eclipse/Eclipse-Platform/assets/119662019/6bd7c7c6-a91c-4856-85d5-8321eba9dc8d)

E.g. if I have a two monitor setup (100% and 200%) and I have everything on 200%, opening the menu works fine, but I would not expect it to have the scrollbars (see screenshot). -> perhaps is the primary monitor zoom involved here
I a detach one view and movie it to 100% (only the one view, not the rest of the IDE), then the menu is not opened anymore. It seems that the detection is not working correctly,  perhaps the mouse position is converted using the DPIUtil zoom (that is on 100% in this scenario) and it does find the elements it is hovering over on the 200% percent monitor

**Comment by ShahzaibIbrahim** [comment]
Issue not reproducible for me @akoch-yatta

**Comment by akoch-yatta** [comment]
Will be solved with #78
