### ISSUE TITLE
Sometimes the menu "freezes" when you change the zoom of the monitor the shell is on

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#95]
Last when when Heiko did a short demo. He had his laptop connected to a beamer and duplicated the content. I think he switched from 100% to 125% percent and his menu got stuck overlaying the top toolbar.

I personally cannot get it reproduced

**Comment by akoch-yatta** [comment]
@HeikoKlare Can you try to reproduce it with your laptop again?

**Comment by HeikoKlare** [comment]
@akoch-yatta You mean this behavior?
![Image](https://github.com/user-attachments/assets/4369aec4-6de3-4d0c-b790-7e1309d906f0)

I can reproduce with current I-Build/master state by changing the scaling of the monitor, on which the workbench window is placed, from, e.g., 100% to 150%

**Comment by ShahzaibIbrahim** [comment]
@HeikoKlare @akoch-yatta I tried the same steps but still not facing this issue. Perhaps I am missing some steps?

**Comment by HeikoKlare** [comment]
I use a plain SDK. Maybe the problem does not occur with the WiP for the ImageBasedFrame? I have not checked that.

**Comment by akoch-yatta** [comment]
I assume that is tied to the restart dialog popping up. @HeikoKlare do you have that behaviour without the dialog as well?

**Comment by HeikoKlare** [comment]
Just tested with today's I-Build, which does not show the restart dialog anymore. Now the issue does not occur for me anymore.

So I close this as (implicitly) resolved. If you still need to issue, feel free to reopen.
